# Generated by Django 6.0.5 on 2026-05-28 06:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('suppliers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(choices=[('cement', 'Cement'), ('iron_bar', 'Iron Bar'), ('nails', 'Nails'), ('wire_mesh', 'Wire Mesh'), ('barbed_wire', 'Barbed Wire'), ('iron_sheet', 'Iron Sheet'), ('wheelbarrow', 'Wheelbarrow'), ('paint', 'Paint')], max_length=50)),
                ('specification', models.CharField(choices=[('cem iiN', 'cem iiN Cement'), ('cem iiiN', 'cem iiiN Cement'), ('10mm', '10mm Iron Bar'), ('12mm', '12mm Iron Bar'), ('16mm', '16mm Iron Bar'), ('27gauge', '27 Gauge'), ('28gauge', '28 Gauge'), ('high_tensile', 'High Tensile'), ('low_tensile', 'Low Tensile')], max_length=100)),
                ('color', models.CharField(blank=True, choices=[('red', 'Red'), ('blue', 'Blue'), ('green', 'Green'), ('black', 'Black'), ('white', 'White'), ('silver', 'Silver')], max_length=50, null=True)),
                ('unit', models.CharField(choices=[('piece', 'Piece'), ('kg', 'Kilogram'), ('bundle', 'Bundle'), ('roll', 'Roll'), ('box', 'Box'), ('bag', 'Bag')], max_length=50)),
                ('buying_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantity', models.PositiveIntegerField()),
                ('available_stock', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='suppliers.supplier')),
            ],
        ),
    ]
